### PR TITLE
Fix kor.yml again

### PR DESCRIPTION
**Pull request by GoodLucky777**
What is "음모 세계"? I think plot translated to word that means story plot, not a ground plot. lol

### CODE REVIEW

**Comment by tim03we** [comment]
It is meant that the player is not in a plot world.

**Comment by tim03we** [comment]
Does your translation agree with that?

**Comment by dongmin-dev** [comment]
Yes . He fixed it ok

**Comment by tim03we** [comment]
With the next major update this will be available on NukkitX.

**Pull request merged**
